# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewFriend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NewFriend
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'NewFriend-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewFriendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
